[package]
name = "sqdr"
version = "0.1.0"
edition = "2021"

authors = ["Cees van de Griend <cees.van.de.griend@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
