name: Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  |
      docker login --user cvdg --password {{ GHCR_TOKEN }} ghcr.io
      docker build . --file Dockerfile --tag sqdr:latest
      docker push ghcr.io/cvdg/sqdr:latest
