name: Build and Push the Docker Image
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u ${{ secrets.GHCR_USER }} -p ${{ secrets.GHCR_TOKEN }} ghcr.io
    - name: Docker build
      run: docker build . -t ghcr.io/cvdg/sqdr:latest
    - name: Docker push
      run: docker push ghcr.io/cvdg/sqdr:latest
